### ISSUE TITLE
where to download the pretrained models ?

### ISSUE THREAD

**Issue by Shuwrood-SSW** [zgcr/pytorch-ImageNet-CIFAR-COCO-VOC-training#1]
where to download the pretrained Regnet models ?

thanks

**Comment by zgcr** [comment]
I am still modifying my code. The pretrained model will be provided after the code is completed.It will takes about one week. Please pay attention to this repository.

> where to download the pretrained Regnet models ?
> 
> thanks

I am still modifying my code. The pretrained model will be provided after the code is completed.It will takes about one week. Please pay attention to this repository.

**Comment by swjtulinxi** [comment]
请问，单张2080ti训练cifar100可以训练出你的效果吗，还有是不是但卡就没法训练imagenet啊，数据集需要自己下载还是这个代码可以自己下载啊

**Comment by zgcr** [comment]
> 请问，单张2080ti训练cifar100可以训练出你的效果吗，还有是不是但卡就没法训练imagenet啊，数据集需要自己下载还是这个代码可以自己下载啊

训练cifar100单卡是可以的，因为cifar100图像是32x32的，很小，单张2080ti就可以用Batch=128了。单卡要训练ImageNet可以使用apex和梯度累加，apex可以在同样显卡的情况下把batch扩大接近一倍，这样要用batch=256时需要的显卡就少了一半，然后再用梯度累加（小Batch多次前向计算梯度加和后一次性反向传播），这个是用时间换显卡。cifar100代码里应该是检测然后自动下载数据集的，ImageNet需要自己下载数据集然后整理成readme里的文件组织结构。

**Comment by swjtulinxi** [comment]
单卡跑cifar100，128可以跑车你表格当作你的效果吗，因为些论文，是不是只跑cifar没什么说服力啊

**Comment by zgcr** [comment]
> 单卡跑cifar100，128可以跑车你表格当作你的效果吗，因为些论文，是不是只跑cifar没什么说服力啊

没看懂什么意思？不过涉及分类的论文一般同时在ImageNet和Cifar100上做实验的比较有说服力。

**Comment by swjtulinxi** [comment]
我是说单卡跑cifar100，bs=128，可以跑出你表格上的效果吗

**Comment by swjtulinxi** [comment]
我看你4卡都要跑4天imagenet，说明我只能跑cifar了

**Comment by zgcr** [comment]
> 我是说单卡跑cifar100，bs=128，可以跑出你表格上的效果吗

可以，我就是单卡跑的cifar，不过需要多跑几次，因为cifar数据集比较小，最佳收敛点的波动会比较厉害，我跑了好几次，最低和最高能差1个百分点左右。

**Comment by swjtulinxi** [comment]
什么是多跑几次，是epochs设置大点？？

**Comment by zgcr** [comment]
> 什么是多跑几次，是epochs设置大点？？

我代码里保存的是200个epoch里最好表现的模型，但是同样的配置重复跑几次，每次保存的最好表现模型性能也会有高低波动的，多跑几次就是这个意思。

**Comment by swjtulinxi** [comment]
好的十分感谢，如果你的代码再加上分割的实验那就更完美了
