### ISSUE TITLE
有关cocodataset的一些问题

### ISSUE THREAD

**Issue by muyihao** [zgcr/pytorch-ImageNet-CIFAR-COCO-VOC-training#11]
你好，我主要想学习COCO数据集的一个加载方式，看见你写的很好，但是对cocodataset中一些内容有疑问，比如coco数据集中COCODataPrefetcher()这个类是干嘛的呢，还有这个文件中的coco_class_color干什么用的呢

**Comment by zgcr** [comment]
COCODataPrefetcher用来在训练过程中进行数据并行预读取，即在本轮迭代时预读取下一轮迭代的输入数据。coco_class_color是预设的80个类的颜色，用来可视化标注框结果时用的。

**Comment by zgcr** [comment]
> 你好，我主要想学习COCO数据集的一个加载方式，看见你写的很好，但是对cocodataset中一些内容有疑问，比如coco数据集中COCODataPrefetcher()这个类是干嘛的呢，还有这个文件中的coco_class_color干什么用的呢

COCODataPrefetcher用来在训练过程中进行数据并行预读取，即在本轮迭代时预读取下一轮迭代的输入数据。coco_class_color是预设的80个类的颜色，用来可视化标注框结果时用的。
