### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by jessony** [zgcr/pytorch-ImageNet-CIFAR-COCO-VOC-training#6]
Could you please share me with your pretrained model of Vovnet series model and RegNet series model? thank you very much!!!!

**Comment by zgcr** [comment]
> Could you please share me with your pretrained model of Vovnet series model and RegNet series model? thank you very much!!!!

I have provided the pretrained models for Vovnet and RegNet. Please download from the link provided in the readme.md.
