### ISSUE TITLE
Difference between DataParallel and DistributedDataParallel?

### ISSUE THREAD

**Issue by zpge** [zgcr/pytorch-ImageNet-CIFAR-COCO-VOC-training#8]
Hi,
Nice work. I have a question. What is the difference between resnet_imagenet_DataParallel_train_example and resnet_imagenet_DistributedDataParallel_train_example?

**Comment by zgcr** [comment]
> Hi,
> Nice work. I have a question. What is the difference between resnet_imagenet_DataParallel_train_example and resnet_imagenet_DistributedDataParallel_train_example?

Non-distributed training mode and distributed training mode.
